---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-bot
# automountServiceAccountToken: false
imagePullSecrets:
- name: registry-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-bot
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-bot
subjects:
- kind: ServiceAccount
  name: deploy-bot
  namespace: default
  # apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: drone-deploy
#   namespace: web

# ---

# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: Role
# metadata:
#   name: drone-deploy
#   namespace: web
# rules:
#   - apiGroups: ["extensions"]
#     resources: ["deployments"]
#     verbs: ["get","list","patch","update"]

# ---

# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: RoleBinding
# metadata:
#   name: drone-deploy
#   namespace: web
# subjects:
#   - kind: ServiceAccount
#     name: drone-deploy
#     namespace: web
# roleRef:
#   kind: Role
#   name: drone-deploy
#   apiGroup: rbac.authorization.k8s.io