apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heimdall
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: heimdall.dev.kube.terabits.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: heimdall
            port:
              number: 80

# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: heimdall
# spec:
#   entryPoints:
#     - websecure
#   routes:
#   - kind: Rule
#     match: Host(`heimdall.dev.kube.terabits.io`)
#     services:
#     - kind: Service
#       name: heimdall
#       port: 80
#       passHostHeader: true
#       responseForwarding:
#         flushInterval: 1ms
#       scheme: https
#       sticky:
#         cookie:
#           httpOnly: true
#           name: cookie
#           secure: true      