---
- name: remove old Docker install
  apt:
    pkg: 
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
    state: absent

- name: remove old Docker install - snap
  shell:
    cmd: snap remove docker

- name: Install a list of packages
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: present

# - name: Add Docker’s official GPG key
#   shell:
#     cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: add repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present

- name: add Docker Group
  shell:
    cmd: groupadd docker
  ignore_errors: yes

- name: add user to Docker Group
  shell:
    cmd: usermod -aG docker $USER
  ignore_errors: yes

# - name: apply changes to group
#   ansible.builtin.shell:
#     cmd: newgrp docker
#   ignore_errors: yes

- name: update owne of docker socket
  file:
    path: /var/run/docker.sock
    group: docker

- name: restart docker service
  shell:
    cmd: systemctl restart docker

# - name: restart docker service - snap
#   ansible.builtin.shell:
#     cmd: systemctl restart snap.docker.dockerd.service