---
# curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
# - name: Get Stable Tag
#   get_url:
#     url: https://dl.k8s.io/release/stable.txt
#     dest: /tmp/kubectl-stable.txt

# - name: Read Stable Tag
#   register: kubectl_stable_tag
#   slurp: 
#     src: "/tmp/kubectl-stable.txt"

# - name: Download k3d binary x64
#   get_url:
#     url: https://dl.k8s.io/release/{{ kubectl_stable_tag['content'] | b64decode }}/bin/linux/amd64/kubectl
#     # checksum: sha256:https://github.com/rancher/k3d/releases/download/{{ k3d_version }}/sha256sum-amd64.txt
#     dest: /usr/local/bin/kubectl
#     owner: root
#     group: root
#     mode: 0755
#   when: ansible_facts.architecture == "x86_64"

- name: Read Stable Tag
  register: kubectl_stable_tag
  uri:
    url: https://dl.k8s.io/release/stable.txt
    method: GET
    return_content: yes

- name: Download k3d binary x64
  get_url:
    url: https://dl.k8s.io/release/{{ kubectl_stable_tag.content }}/bin/linux/amd64/kubectl
    # checksum: sha256:https://github.com/rancher/k3d/releases/download/{{ k3d_version }}/sha256sum-amd64.txt
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: 0755
  when: ansible_facts.architecture == "x86_64"

