---
- name: Copy k8s kubeconfig file
  shell:
    cmd: k3d kubeconfig get {{ cluster_name }} > ~{{ ansible_user }}/.kube/config

- name: Update kubeconfig file authoriations
  file:
    path: ~{{ ansible_user }}/.kube/config
    state: file
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=,o="

- name: Wait for traefik pods become ready
  register: traefik_pods_ready
  command: "kubectl wait -n kube-system --for=condition=available deployment/traefik --timeout=600s"
  retries: 10
  delay: 10
  until: traefik_pods_ready.stdout.find("condition met") != -1

- debug: var=traefik_pods_ready.stdout_lines

- name: Add Helm Chart Repos
  community.kubernetes.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.repo_url }}"
  loop:
    - { name: 'traefik', repo_url: 'https://helm.traefik.io/traefik' }
    - { name: 'jetstack', repo_url: 'https://charts.jetstack.io' }
    - { name: 'rancher-stable ', repo_url: 'https://releases.rancher.com/server-charts/stable' }

# - name: Deploy Helm - Rancher
#   community.kubernetes.helm:
#     name: rancher
#     chart_ref: rancher-stable/rancher
#     chart_version: 2.5.5
#     release_namespace: cattle-system
#     values:
#       hostname: rancher.{{ cluster_domain }}
#     wati: true
