apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: hareeshbabu82@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - terabits.io
      dns01:
        route53:
          region: us-west-1
          accessKeyID: AKIAQDF5NRMQUYOZEKMB
          secretAccessKeySecretRef:
          # kubectl create secret generic route53-access-key --from-literal=access-key=XYZ
            name: route53-access-key
            key: access-key